In [1]:
#Para esta actividad se importarán las siguientes librerías:
#Para esta actividad se importarán las siguientes librerías:
import pandas as pd
#Importando las librerías para el ejemplo 
import matplotlib.pyplot as plt #Importando  matplotlib
import numpy as np #Importando numoy
import seaborn as sns #Importando seaborn

#Importando dataset que se van a usar
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

#Para poder realizar la normalización media se debe de importar el escalador
from sklearn.preprocessing import StandardScaler, RobustScaler

In [2]:
#Código para cargar el Dataset
enfermedadesCardiovascular= pd.read_csv('cardio_train.csv',sep=";")
enfermedadesCardiovascular.head() #presentando dataset

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0